services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nubla_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: nubla_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "512m"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=yourpassword
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: "2g"
        reservations:
          memory: "1g"
    restart: unless-stopped

  log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=nubla_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=nubla_db
    command: >
      bash -c "sleep 90 && python ingestion/generate_test_logs.py /app/ingestion/test_logs.txt 5000 30 && python ingestion/insert_logs_to_postgres.py /app/ingestion/test_logs.txt"
    deploy:
      resources:
        limits:
          memory: "512m"
        reservations:
          memory: "256m"

  log-syncer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - log-generator
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=nubla_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=nubla_db
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=yourpassword
    command: >
      bash -c "sleep 120 && python ingestion/sync_to_elasticsearch.py"
    deploy:
      resources:
        limits:
          memory: "512m"
        reservations:
          memory: "256m"

volumes:
  postgres_data:
    driver: local
  esdata:
    driver: local